.TH "dynlink_impl_interface" 3 "Sun Jun 30 2024" "Version 0.8.0.76f02c051c9b" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_impl_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/TtEL\-Notepad/TtEL\-Notepad/core/source/dynlink/include/dynlink/dynlink_interface\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdynlink_impl_interface_extension\fP \fBextension\fP"
.br
.ti -1c
.RI "\fBdynlink_impl_interface_get_name\fP \fBget_name\fP"
.br
.ti -1c
.RI "\fBdynlink_impl_interface_load\fP \fBload\fP"
.br
.ti -1c
.RI "\fBdynlink_impl_interface_symbol\fP \fBsymbol\fP"
.br
.ti -1c
.RI "\fBdynlink_impl_interface_unload\fP \fBunload\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBdynlink_impl_interface_extension\fP dynlink_impl_interface::extension"

.SS "\fBdynlink_impl_interface_get_name\fP dynlink_impl_interface::get_name"

.SS "\fBdynlink_impl_interface_load\fP dynlink_impl_interface::load"

.SS "\fBdynlink_impl_interface_symbol\fP dynlink_impl_interface::symbol"

.SS "\fBdynlink_impl_interface_unload\fP dynlink_impl_interface::unload"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
