.TH "log_policy_storage_batch_ctor" 3 "Sun Jun 30 2024" "Version 0.8.0.76f02c051c9b" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_storage_batch_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/TtEL\-Notepad/TtEL\-Notepad/core/source/log/include/log/log_policy_storage_batch\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t log_policy_storage_batch_ctor::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
